version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    container_name: fcc-angular-typescript
    command: "tail -f /dev/null"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
